### PR TITLE
Gate plot lw

### PR DESCRIPTION
**Pull request by yoavram**
Added an argument to plot to allow setting the line width of the gate plots - this is because sometimes the default (1?) is too think to show, especially (I think) when using `alpha` for the scatter plot.

### CODE REVIEW

**Comment by yoavram** [comment]
Note that this branch is based on the `parse_number_by_col` branch.

**Comment by eyurtsev** [comment]
This will change default line widths that may be set by matplotlib, but I don't think it's important. (A workaround makes the code too complicated, so it's not worth it.) 

i.e.,

plot([1, 2, 3], lw=None) is not a valid matplotlib command, even though one would naively expect it to assign the default linewidth

**Comment by eyurtsev** [comment]
Fixed iterable in the following commit

https://github.com/eyurtsev/FlowCytometryTools/commit/0999cd41dbf16af564cf4352f74d97266aec649c

**Comment by yoavram** [comment]
Great! Thanks.

**Pull request merged**
